language: node_js
node_js:
  - 12
script:
  - npm run test:coverage -- --verbose
after_script:
  - echo "------------------------------"
  - cat coverage/coverage-final.json
  - echo "------------------------------"
  - npm run coveralls
